### PR TITLE
Discussion: Move to Github Actions

### PR DESCRIPTION
**Pull request by dfridkin**
Pro-tip: ignore the commits tab because i did a lot of reversion -- just look at files changed.

There are 2 major reasons I think the CI services for this repo should move from Travis to GitHub Actions: speed, and artifact storage.

#### Speed
[Travis](https://docs.travis-ci.com/user/reference/overview/#virtualisation-environment-vs-operating-system) and [Github Actions](https://help.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners#supported-runners-and-hardware-resources) have very similar environments.

|   |  Travis CI | GitHub Actions |
|---|---|---|
| OS | Ubuntu 18.04 | Ubuntu 18.04 |
| Memory | 7.5GB | 7GB |
| CPU Cores  | 2 | 2 |
| Storage  | 50GB | 14GB |

Travis wins on Memory -- barely -- and storage, which is kind of useless for this project since we don't have humongous build dependencies or anything like that. The point is, there's no real obvious hardware advantage on one provider over the other. So, to test the effectiveness of each, I created equivalent [GitHub Actions](https://github.com/datafruits/datafruits/compare/master...dfridkin:ci-coverage?expand=1#diff-e9f950f17198d3d5e3122a44230a09b9) and [Travis CI](https://github.com/datafruits/datafruits/compare/master...dfridkin:ci-coverage?expand=1#diff-354f30a63fb0907d4ad57269548329e3) configurations.

These configurations have 3 jobs:

- Lint the files
- Test the files and upload coverage (#428)
- Run [Lighthouse CI](https://github.com/GoogleChrome/lighthouse-ci)

I reverted the commits from #428 for the purposes of this PR, however [this Travis CI run](https://travis-ci.org/github/dfridkin/datafruits/builds/694884630) and [this Github Actions run](https://github.com/dfridkin/datafruits/actions/runs/125523331) both ran the tests that I wrote. Here's the time breakdown for each provider:

|   |  Travis CI | GitHub Actions |
|---|---|---|
| Lint files | 2:48 | 3:09 |
| Test files | 6:53 | 5:15 |
| Lighthouse  | 6:57 | 5:58 |
| **Total**  | **7:14** | **6:17** |

As you can see, Actions saves about a minute over Travis, and this difference will likely grow as more tests get written. "Ok," I hear you say. "So Actions is faster by about a minute. Big whoop. So what?" I'm glad you asked, friend.

#### Artifact Storage

This, in my opinion, is enough reason to switch to Actions.

With the Travis run, you have to ([unless you pay for S3](https://docs.travis-ci.com/user/uploading-artifacts/)) [upload your lighthouse report to GCP](https://github.com/GoogleChrome/lighthouse-ci/blob/master/docs/configuration.md#target) and [search through `stdout` for the url](https://travis-ci.org/github/dfridkin/datafruits/jobs/694884633#L599).

With Actions, you just [go to the run](https://github.com/dfridkin/datafruits/actions/runs/125523331) and you can download the report right from there. There's actually a [dedicated action](https://github.com/marketplace/actions/lighthouse-check), but in the spirit of fairness I used [`lhci`](https://www.npmjs.com/package/@lhci/cli) on both. You can see that you can also download the coverage report, and conceivably could also store build output for a deployment step.

### CODE REVIEW

**Comment by mcfiredrill** [comment]
Thank you again for writing all this up @dfridkin .
To be totally honest I don't know exactly how much performance of CI is an issue at this point, but its great to know the statistics!

One thing I do miss from Travis is the status checks that are applied to the PR (the little green checkmark). Do you have any idea if github actions can do the same thing?

I am excited about being able to run performance checks like lighthouse though.
It would also be cool to run lighthouse reports and see if a PR increased or decreased performance directly.

**Comment by dfridkin** [comment]
> Thank you again for writing all this up @dfridkin .
To be totally honest I don't know exactly how much performance of CI is an issue at this point, but its great to know the statistics!

Of course!

> One thing I do miss from Travis is the status checks that are applied to the PR (the little green checkmark). Do you have any idea if github actions can do the same thing?

It does! It's automatically integrated with github 😊. You can configure certain jobs and workflows to run on pushes, pull requests, and a few other event triggers, as well as any custom webhook.

> I am excited about being able to run performance checks like lighthouse though.
> It would also be cool to run lighthouse reports and see if a PR increased or decreased performance directly.

This is absolutely something we can do! It's built in to the Github Action and I'm sure we could configure it on travis automatically. We could also do the same thing for the coverage, to see if a PR increases or decreases code coverage.

**Comment by mcfiredrill** [comment]
> It does! It's automatically integrated with github blush. You can configure certain jobs and workflows to run on pushes, pull requests, and a few other event triggers, as well as any custom webhook.

Ah ok cool, I didn't see the status check from github actions on this PR, only travis so I was just wondering when that kicks in.

**Comment by dfridkin** [comment]
I believe that's because `.github/workflows/ci.yml` only exists in my PR, and not in the upstream. My repo has status checks from both travis and github actions.

**Comment by mcfiredrill** [comment]
> I believe that's because .github/workflows/ci.yml only exists in my PR, and not in the upstream.

Looks like you're right. I set it up on this fork to test it out, if anyone else wants to check out what it looks like you can look at this PR:
https://github.com/mcfiredrill/datafruits/pull/5

**Comment by mcfiredrill** [comment]
This seems to be working well in my test repo, I think I am pretty much ready to merge it. 

Do you think you can fix the conflicts in the package.json file @dfridkin  ?

**Comment by mcfiredrill** [comment]
Thanks @dfridkin

**Comment by mcfiredrill** [comment]
Going to merge this unless anyone has any objections. 
I have a few things I want to try and improve that I will make separate issues for, but seems like a great start. Thanks again @dfridkin :tada:

**Comment by dfridkin** [comment]
Of course! Glad you found it helpful :)

**Pull request merged**
