### PR TITLE
Add raining cats and dogs to the weather selector.

### PR DESCRIPTION
**Pull request by sylvillain**
~~Still in progress, there's a bug with rendering the two types of textures. Probably gonna check it out later this evening.~~

This PR adds another option to the weather dropdown on the bottom right, allowing you to make it rain CATS AND DOOOOOGGGGSSSSS. It has been a minute since I've written javascript and I've not done anything with PIXI.js so the add child stuff and modifying the particleContainer to a container of containers is kinda funky, but the best code is the code that does the job and wowzer do those puppies and kitties fly. 

image

### CODE REVIEW

**Comment by mcfiredrill** [comment]
holy cow this is awesome

**Comment by mcfiredrill** [comment]
Seems to work alright ! https://deploy-preview-1253--datafruitsfm.netlify.app/chat
Where are the sprites from are those OK to use ? Not that I've been super strict about that kinda thing to begin with. :grimacing:

**Comment by sylvillain** [comment]
the sprites came from yours truly :) they're the default Arial emoji cat/dog from gimp

**Review by dudethatbe — APPROVED** [review]
Looks good to me 👍 I was able to cycle through the 3 weather options fine. We don't need to resolve it here, but the animation gets considerably slower on each cycle.

**Pull request merged**
