### PR TITLE
redo subscribe and search sections

### PR DESCRIPTION
**Pull request by dudethatbe**
So I'm working on making the archives page a little easier to use:

image

this looks fine on a small window, but not so much when you fullscreen 😅

image

### CODE REVIEW

**Comment by dudethatbe** [comment]
image
 latest looks 💈 lmk what you think

**Comment by mcfiredrill** [comment]
Pagination at the top is good! Very helpful. :100: 
And yeah links for the podcast apps looking good.

Still not sure how I feel about centering everything, seems like it's easier to read if it's left aligned.

Should 'Archives' be bigger font size, and maybe also Debussy?

**Comment by dudethatbe** [comment]
Yeah I agree than centering it all is probably more awkward than having it left-aligned (like the rest of the contents below. Also yeah I meant to do something with the Archives title 😅 Was also wondering if you saw that I duplicated the pagination. Will that cause issues? Seems like it would be ideal to somehow share the same interface, but I'm not good enough at ember to figure that one out on my own..

**Comment by mcfiredrill** [comment]
Duplicating it is fine, if it appears on the screen twice I should see it in the code twice, makes sense to me. :sweat_smile:

**Comment by rbxbx** [comment]
I think this looks good!!!!

only thing i might suggest -- could we make the show title font the same line height as the tags? it's kinda weird imo how much smaller it is now 

see now:
Screen Shot 2022-10-14 at 13 52 47

vs something like: 
Screen Shot 2022-10-14 at 13 58 56

the positioning is still a lil off, but i think it's more visually cohesive ?

**Comment by dudethatbe** [comment]
Alright I think this about does it for the archives page. I fixed up the titles of the archives and the play/download buttons. Moved the items in Search/Subscribe to be aligned to the left. And also made the Archives header really big

**Comment by rbxbx** [comment]
> Alright I think this about does it for the archives page. I fixed up the titles of the archives and the play/download buttons. Moved the items in Search/Subscribe to be aligned to the left. And also made the Archives header really big

you fixed the alignments too!!! looks so good! 🙏

**Review by rbxbx — APPROVED** [review]
🌈

**Review by mcfiredrill — APPROVED** [review]
Looking real good thanks pal

**Comment by mcfiredrill** [comment]
note: probably want all the other page's <h1> headings to be as big as this one to match, but we can do that in another PR :alien:

**Comment by dudethatbe** [comment]
For sure! I can work on making the pages more uniform by making classes instead of copy pasting the same tailwind classes into every template lol

**Comment by dudethatbe** [comment]
ok i _really_ did it this time time. pretty much went through all of the pages and made them all look similar. the DJ sign up page was weird, the background takes up the whole page unlike the rest of the changes (like archives, timetable, etc.), but at least its easier to look at now.
speaking of hard things to read, I also re-worded some of our About text. I'm fairly sure this is it for the PR unless anyone else has any other requests!

**Comment by dudethatbe** [comment]
Thanks! I'm gonna call it here and say I'm done with it. There were a few little things I just posted, but any new requests should be a in a new branch at this point 🌿

**Pull request merged**
