### PR TITLE
disconnect from video 

### PR DESCRIPTION
**Pull request by dudethatbe**
I recently added a button that hides/shows the video, primarily for accessibility. Being able to turn it off if you're sensitive to flashing lights is a plus, but the video data is still being received by the user. This may be fine on a desktop device, or you have unlimited data, but if you're limited on bandwidth then this would be a big bummer.

The video library has been a pain and doesn't allow a straightforward way of turning the video off and back on again https://github.com/videojs/video.js/issues/5312

The best I can do without getting into a mess of spaghetti is to simply allow the one-time operation of disconnecting the video 🤷‍♀️ A confirmation dialog will appear and notify the user that they can refresh the page if they want to reconnect. I just need to add the messaging to the translations then this should be ready.

One could argue that if you're on a mobile device, and are looking to consume as little data as possible, then you could listen through RadioGarden or whatever, and chat through Discord. But that chat bridge isn't always running so maybe this is our best choice for now.

As always, I'm open to suggestions. 

demonstrating that you can hide/show the video and turn it off after confirming

### CODE REVIEW

**Comment by mcfiredrill** [comment]
It sounds like it will buffer a default max of 60 seconds if the video is paused, any confirm on this behaviour?
https://github.com/videojs/video.js/issues/5312

**Comment by bradwbradw** [comment]
Maybe this isn't as fun, but why not start with video off (unplugged), then you only need one button to "plug it in and turn it on"?  Maybe the action can be saved in local storage, so if a user turns it on, it defaults to "on" next time they load on the same device.

This might have more benefit than a mute button / unplug button, because in low-bandwidth environments, the slowdown has already been experienced while the page has been loading, before the user can click on the button.

There's still more to consider with the opt-in approach, but I wanted to share my thoughts

**Comment by mcfiredrill** [comment]
Working on my take on it here https://github.com/datafruits/datafruits/pull/1099

**Comment by dudethatbe** [comment]
Thanks for weighing in @bradwbradw 🙂 your idea of storing this choice in localstorage sounds like the ideal solution to this. Not only could we prevent the video from loading in the first place, but we could prevent loading other assets to cut down on bandwidth usage.

**Comment by dudethatbe** [comment]
Changing focus to #1099 ➡ After spending more time reading the comments, we saw that after pausing and waiting for 60s, that the video data will not be transmitted. It will continually poll for the metadata, but this is a few hundred bytes (opposed to ~5mb for the video data).
This feels like a "good enough" solution for now, but this @mcfiredrill  linked me this after talking about low-bandwidth cases 
https://developer.mozilla.org/en-US/docs/Glossary/Progressive_Enhancement

**Pull request closed without merging**
