### PR TITLE
CoC Checkbox

### PR DESCRIPTION
**Pull request by dudethatbe**
I'm thinking there should be some acknowledgement from anyone joining the chat that we expect them to be nice 🚸 This adds a checkbox to the chat login that works with the nickname input. If it's at least two characters long and they have checked the box, then the _Join chat_ button will be enabled. The **CoC** is an <abbr> element that also has a link to the CoC page. This way it show the title of CoC and quickly redirect them. It might be an accessibility issue to combine <a> and <abbr> in this way though. There's an issue where the label for checkbox doesn't appear if you're in mobile, otherwise it seems to work out fine. 
image

### CODE REVIEW

**Comment by mcfiredrill** [comment]
This looks great, love this idea. 💟

**Comment by dudethatbe** [comment]
Thanks, I will be working on re-wording the agreement label. Seems like we just need to make it clear that they are agreeing to being banned from the chat _if_ they act like a dingle. My only concerns will be the translations. I usually just use Google for translating these labels, do you have any other/better resources for this @mcfiredrill ?

**Comment by mcfiredrill** [comment]
> . I usually just use Google for translating these labels, do you have any other/better resources for this @mcfiredrill ?

I think we can use machine translation for now and fix them with native suggestions when we get around to it.

**Comment by mcfiredrill** [comment]
closing in favor of https://github.com/datafruits/datafruits/pull/584

**Pull request closed without merging**
