### PR TITLE
Fixed all template linting issues

### PR DESCRIPTION
**Pull request by sharpshark28**
Assisting in getting closer to green builds again <3

```bash
yarn lint:hbs
```

## Before: 
Screen Shot 2020-01-23 at 10 00 55 PM

## After:
Screen Shot 2020-01-23 at 9 58 53 PM

---

## How to QA this

This touches a ton of files. The best things to QA are localized text strings because while I did try to be careful, I did move well over a hundred bits of localized text by hand to the english translations file. Look for "Missing loc" or whatever it says throughout the site - especially on text heavy pages like CoC and About.

### CODE REVIEW

**Comment by mcfiredrill** [comment]
This looks great ! Thank you for this work. It will be great to have all the text in i18n.

I will merge after I do a bit of manual QA.

> I did move well over a hundred bits of localized text by hand to the english translations file. Look for "Missing loc" or whatever it says throughout the site - especially on text heavy pages like CoC and About.

I think it should fall back to English if there is no translation? Which seems fine for certain things like "Soundcloud" etc.

**Comment by sharpshark28** [comment]
> This looks great ! Thank you for this work. It will be great to have all the text in i18n.
> 
> I will merge after I do a bit of manual QA.
> 
> > I did move well over a hundred bits of localized text by hand to the english translations file. Look for "Missing loc" or whatever it says throughout the site - especially on text heavy pages like CoC and About.
> 
> I think it should fall back to English if there is no translation? Which seems fine for certain things like "Soundcloud" etc.

Yes indeed, in my experience it should fall back to English translations if there's no unique translation for a user's chosen language. Although that'd be worth QA'ing real quick.

**Comment by mcfiredrill** [comment]
I did some testing and the site seemed fine.

I tired to run the ember-template-lint command and I still got some errors. Seems to be mostly just indentation stuff.
```
 tony@dokkebi  ~/src/datafruits  ➦ 452ee83 ●  yarn lint:hbs

yarn run v1.21.1
$ ember-template-lint .
/home/tony/src/datafruits/app/templates/components/datafruits-chat-input-message.hbs
  14:26  error  Incorrect indentation of close bracket '>' for the element '<button>' beginning at L14:C26. Expected '<button>' to be at L14:C0.  attribute-indentation
  19:12  error  Incorrect indentation of htmlAttribute 'class' beginning at L19:C12. Expected 'class' to be at L20:C6.  attribute-indentation
  20:33  error  Incorrect indentation of close bracket '>' for the element '<button>' beginning at L20:C33. Expected '<button>' to be at L21:C4.  attribute-indentation

/home/tony/src/datafruits/app/templates/components/datafruits-chat.hbs
  48:6  error  Incorrect indentation of close bracket '>' for the element '<button>' beginning at L48:C6. Expected '<button>' to be at L47:C6.  attribute-indentation

/home/tony/src/datafruits/app/templates/components/datafruits-player.hbs
  36:6  error  Incorrect indentation of close bracket '>' for the element '<a>' beginning at L36:C6. Expected '<a>' to be at L35:C6.  attribute-indentation
  44:4  error  Incorrect indentation of close bracket '>' for the element '<span>' beginning at L44:C4. Expected '<span>' to be at L43:C4.  attribute-indentation

/home/tony/src/datafruits/app/templates/components/datafruits-visuals.hbs
  13:9  error  Incorrect indentation of htmlAttribute 'href' beginning at L13:C9. Expected 'href' to be at L14:C8.  attribute-indentation
  13:56  error  Incorrect indentation of htmlAttribute 'target' beginning at L13:C56. Expected 'target' to be at L15:C8.  attribute-indentation
  13:72  error  Incorrect indentation of htmlAttribute 'rel' beginning at L13:C72. Expected 'rel' to be at L16:C8.  attribute-indentation
  13:86  error  Incorrect indentation of close bracket '>' for the element '<a>' beginning at L13:C86. Expected '<a>' to be at L17:C6.  attribute-indentation

/home/tony/src/datafruits/app/templates/components/giphy-loader.hbs
  1:8  error  Incorrect indentation of positional param 'hash' beginning at L1:C8. Expected 'hash' to be at L2:C2.  attribute-indentation

/home/tony/src/datafruits/app/templates/components/giphy-search.hbs
  18:10  error  Incorrect indentation of close bracket '>' for the element '<img>' beginning at L18:C10. Expected '<img>' to be at L18:C8.  attribute-indentation

/home/tony/src/datafruits/app/templates/components/pc-nav.hbs
  8:6  error  Incorrect indentation of close bracket '>' for the element '<a>' beginning at L8:C6. Expected '<a>' to be at L7:C6.  attribute-indentation
  13:15  error  Incorrect indentation of close bracket '>' for the element '<span>' beginning at L13:C15. Expected '<span>' to be at L13:C8.  attribute-indentation

/home/tony/src/datafruits/app/templates/components/podcast-track.hbs
  15:7  error  Incorrect indentation of htmlAttribute 'class' beginning at L15:C7. Expected 'class' to be at L16:C6.  attribute-indentation
  15:32  error  Incorrect indentation of htmlAttribute 'href' beginning at L15:C32. Expected 'href' to be at L17:C6.  attribute-indentation
  15:55  error  Incorrect indentation of htmlAttribute 'target' beginning at L15:C55. Expected 'target' to be at L16:C6.  attribute-indentation
  15:71  error  Incorrect indentation of htmlAttribute 'rel' beginning at L15:C71. Expected 'rel' to be at L17:C6.  attribute-indentation
  15:85  error  Incorrect indentation of close bracket '>' for the element '<a>' beginning at L15:C85. Expected '<a>' to be at L18:C4.  attribute-indentation

/home/tony/src/datafruits/app/templates/container/show.hbs
  6:3  error  Incorrect indentation of htmlAttribute 'class' beginning at L6:C3. Expected 'class' to be at L7:C2.  attribute-indentation
  6:16  error  Incorrect indentation of htmlAttribute 'href' beginning at L6:C16. Expected 'href' to be at L8:C2.  attribute-indentation
  6:46  error  Incorrect indentation of htmlAttribute 'target' beginning at L6:C46. Expected 'target' to be at L9:C2.  attribute-indentation
  6:62  error  Incorrect indentation of htmlAttribute 'rel' beginning at L6:C62. Expected 'rel' to be at L10:C2.  attribute-indentation
  6:77  error  Incorrect indentation of htmlAttribute 'aria-label' beginning at L6:C77. Expected 'aria-label' to be at L11:C2.  attribute-indentation
  6:109  error  Incorrect indentation of close bracket '>' for the element '<a>' beginning at L6:C109. Expected '<a>' to be at L7:C0.  attribute-indentation

/home/tony/src/datafruits/app/templates/home/coc.hbs
  85:7  error  Incorrect indentation of htmlAttribute 'href' beginning at L85:C7. Expected 'href' to be at L86:C6.  attribute-indentation
  85:58  error  Incorrect indentation of htmlAttribute 'target' beginning at L85:C58. Expected 'target' to be at L87:C6.  attribute-indentation
  85:74  error  Incorrect indentation of htmlAttribute 'rel' beginning at L85:C74. Expected 'rel' to be at L88:C6.  attribute-indentation
  85:88  error  Incorrect indentation of close bracket '>' for the element '<a>' beginning at L85:C88. Expected '<a>' to be at L89:C4.  attribute-indentation

/home/tony/src/datafruits/app/templates/home/subscribe.hbs
  40:16  error  Incorrect indentation of close bracket '>' for the element '<div>' beginning at L40:C16. Expected '<div>' to be at L40:C10.  attribute-indentation
  44:16  error  Incorrect indentation of close bracket '>' for the element '<div>' beginning at L44:C16. Expected '<div>' to be at L44:C10.  attribute-indentation

/home/tony/src/datafruits/app/templates/components/container/datafruits-player.hbs
  29:6  error  Incorrect indentation of close bracket '>' for the element '<a>' beginning at L29:C6. Expected '<a>' to be at L28:C6.  attribute-indentation
  37:4  error  Incorrect indentation of close bracket '>' for the element '<span>' beginning at L37:C4. Expected '<span>' to be at L36:C4.  attribute-indentation

✖ 33 problems (33 errors, 0 warnings)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about
```
Are you getting the same output in your environment?
Wish there was a command to fix these automatically...

**Comment by sharpshark28** [comment]
@mcfiredrill oh! Huh, not sure why those didn't come up before haha. My machine totally shows these warnings. Fixed all of these in 57d54ad

**Comment by mcfiredrill** [comment]
Great, looking good now! :100: 
```
 tony@dokkebi  ~/src/datafruits  ➦ 57d54ad  yarn lint:hbs

yarn run v1.21.1
$ ember-template-lint .
Done in 5.40s.

```

**Pull request merged**
