### PR TITLE
rename to archives

### PR DESCRIPTION
**Pull request by dudethatbe**

### CODE REVIEW

**Comment by mcfiredrill** [comment]
Looks great, I think there are a couple of instances of using the word 'podcast' we could probably change?
```
 ag podcast translations/en.json 
15:    "latest_podcasts": "LATEST PODCASTS",
65:  "podcasts": {
66:    "title": "Podcasts",
71:    "link_podcastsapp": "Podcasts.app",
89:      "podcastsapp": "Podcasts.app",
93:      "title": "Search for podcasts by upload title using text input",
94:      "tag": "Busque podcasts por título de carga utilizando el ingreso de texto"
212:    "podcasts": "Podcasts",
217:    "archive": "Listen back to the podcast"
```

**Comment by dudethatbe** [comment]
closes #585

**Comment by dudethatbe** [comment]
I left the `Podcasts.app` reference alone since that's actually the name of the podcast app, but that should be it! I also noticed the placeholder for the tags search is incorrectly set to the placeholder for the titles:
datafruits podcasts page

Not to get too far off-track with this branch, but I saw how wonky the Subscribe page looked:
datafruits subscribe page

The only thing I felt unsure about was the changed text that's displayed when you click on a show. The wording of "Listen to the archive" feels generic enough to be translatable, but I'm no linguist. I also think the shows page could use some more work, but I'll stop before I change everything when this was originally about renaming `podcasts` to `archives` 😅 In a nutshell, there's a lot of repeated text, and headings. If you copy and paste the text from the page it looks like:
```

thanks1
Hosted by: thanks1
01-07-2021 Thursday 21:00 EST

Listen to the archive 🍍
▶︎ thanks1 - Best of 2020 - 01072021 house filter house nudisco disco house
Listen back to thanks1 - 08012021 on datafruits 
```
I think all of those elements could be factored down to show less text and all be included within the cool box @4lp made

**Comment by mcfiredrill** [comment]
Looks great! Thanks for changing all the languages too.

I agree with all your other comments, it could all use some fresh paint. I'll make some more issues to work on those.

**Pull request merged**
