### PR TITLE
Add podcast pagination

### PR DESCRIPTION
**Pull request by slaponicus**
Got podcast pagination working, set to 20/page right now.

Issues:
- Can't figure out how to chain the `resetPagination` action to the power-select-multiple onchange handler or make a custom action since the onchange action uses `mut`. Therefore, the pagination doesn't reset when you select an option from the dropdown, only when you type a letter. Pagination should reset everywhere else it's expected to though.
- Do we need some additional CSS for the pagination list?

### CODE REVIEW

**Comment by mcfiredrill** [comment]
Awesome! I'll take a look at this ASAP. Thanks again :)

**Comment by slaponicus** [comment]
oh yeah, that looks super simple to set up!

would you like me to take care of the CSS & remote pagination once you have it set up on the back-end? I totally have the time to do so

**Comment by mcfiredrill** [comment]
Sure if you have time. The CSS could be done now if you have the time.
I will let you know when the remote is setup to accept the `page?` query string.

**Comment by mcfiredrill** [comment]
@slaponicus The API is working with the `page` parameter now, it should be possible to change to use the remote pagination API now.
https://datafruits.streampusher.com/podcasts/datafruits.json?page=4

**Comment by slaponicus** [comment]
rad, thanks! I'll try and tackle this in the next couple of days

**Comment by slaponicus** [comment]
hey @mcfiredrill,

I think we need some pagination information to be returned by the API too. at least something like `total_pages` is required for the pagination list to display the correct number of available pages.

**Comment by mcfiredrill** [comment]
@slaponicus Ah sorry to drop the ball on this, I just saw your comment. 
I'll look into adding that metadata to the API!

**Comment by mcfiredrill** [comment]
I added `pages` and `total_pages` to the API response!
https://datafruits.streampusher.com/podcasts/datafruits.json?page=4

**Comment by slaponicus** [comment]
awesome, thanks! I'll get back on this

**Comment by mcfiredrill** [comment]
@slaponicus if its ok I'm going to merge this for now since I'm only seeing the first page of the podcasts on the site now, oops. 

I'm still down for a PR on updating the CSS for the pagination.

Thanks alot again for your work on this!

**Comment by slaponicus** [comment]
go for it! I ended up having to roll my own pagination since that plugin doesn't work well with models that have `hasMany` fields so it's taking a bit longer than I originally thought

I'll hop on the CSS first though - that definitely won't take long 

No problem! It's been a lot of fun helping out :)

**Comment by slaponicus** [comment]
@mcfiredrill alright, I got remote pagination working (soooo much easier without the external library) but it looks like the server isn't set up to handle filter requests - I think this was all done client-side before we started working on the pagination, right? 

as such it only filters podcasts for your current page, which probably isn't the expected behavior

I can make a PR for what I have so far if you want though - this would fix the issue present on the live site right now 

sorry if this has been a little more involved than you originally thought!

**Comment by slaponicus** [comment]
ack, sorry, one more thing - it looks like `meta.pages` is being returned as a string whereas `meta.total_pages` is an int. Could we return both of them as the same data type? I'm using [ember-truth-helpers](https://github.com/jmurphyau/ember-truth-helpers) to see if we're on the current page, but it uses  `===` to check for equivalence. 

no worries if not - it's mostly just a style thing since Ember is good about not reloading data unnecessarily

**Comment by mcfiredrill** [comment]
> @mcfiredrill alright, I got remote pagination working (soooo much easier without the external library) but it looks like the server isn't set up to handle filter requests - I think this was all done client-side before we started working on the pagination, right?

> as such it only filters podcasts for your current page, which probably isn't the expected behavior

Yeah I was doing all the filtering clientside so nothing on the API for that yet. It might be good to have it server side as well , or at least it would be nice to have the filtering in the query string so its linkable.

> I can make a PR for what I have so far if you want though - this would fix the issue present on the live site right now

Definitely I'd love to see it! And would be great to fix the issue on the site as soon as we can.

**Comment by mcfiredrill** [comment]
> ack, sorry, one more thing - it looks like meta.pages is being returned as a string whereas meta.total_pages is an int. Could we return both of them as the same data type? I'm using ember-truth-helpers to see if we're on the current page, but it uses === to check for equivalence.

I'll change them to both return ints.

Thanks again for all your work!

**Comment by slaponicus** [comment]
ok, the remote pagination should work now and the styles should be consistent with the rest of the site. let me know if there's anything I need to change. the update on the back end makes the current page functionality work great too!

**Comment by mcfiredrill** [comment]
This looks great! 
We can work on the filtering and some other refactorings later maybe, but its working great now!
Thanks again for all your hard work! I'm going to merge this.

**Pull request merged**
