### PR TITLE
Replace moment 2

### PR DESCRIPTION
**Pull request by mcfiredrill**
Fixing some conflict from https://github.com/datafruits/datafruits/pull/546 and updating new code to use dayjs

### CODE REVIEW

**Comment by mcfiredrill** [comment]
bundle_analyze

Not sure if I'm doing this right, no trace of daysjs in the output. Maybe it really is that small.

Moment is totally removed now as well.

**Comment by 4lp** [comment]
it's 2kb so you should see it - can you use the filter in the sidebar? iirc that's a feature of the webpack bundle analyzer, which is what it looks like you're using

**Comment by mcfiredrill** [comment]
I'm using this, not sure if there's a filter
https://github.com/kaliber5/ember-cli-bundle-analyzer#usage

**Review by hergaiety — APPROVED** [review]

**Review by hergaiety — COMMENTED** [review]
Oops close - I'll see if I can fix the failing unit test, should be easy.

**Pull request merged**
