### PR TITLE
add CoC checkbox to the dj inquiry form

### PR DESCRIPTION
**Pull request by mcfiredrill**
closes https://github.com/datafruits/datafruits/issues/502

### CODE REVIEW

**Comment by dudethatbe** [comment]
Was the intention to have the Send button be disabled until the CoC checkbox was checked? I saw the earlier commit that says it should be disabled, but you can submit it without checking the control. Theres a lot of ways of going about it, ideally the CoC could be embedded. It's not obvious all of the fields will still have their values if you navigate away from the page and may dissuade someone from clicking on an unknown link.

**Comment by mcfiredrill** [comment]
> Was the intention to have the Send button be disabled until the CoC checkbox was checked? I saw the earlier commit that says it should be disabled, but you can submit it without checking the control. 

Yeah, I think its not working yet.

>  I guess it opens a new tab which is fine.

I think it might be fine for a first version, embedding the CoC might be better in the future though.

> making the links the same color as the text makes it hard to predict stuck_out_tongue_winking_eye

Agreed....it could at least be underlined....

**Comment by dudethatbe** [comment]
I'll takeover this ticket if that's fine and see what can be done with the link. I'll try compromising and adding a title to the link to show the user it will open it in a new tab

**Comment by dudethatbe** [comment]
Tested this locally and it works out for me. If you try submitting an application without checking the box, then it will notify you to make the modification. This doesn't require any further modifications and will be good for now

**Review by dudethatbe — COMMENTED** [review]
Looks good to me 😊

**Comment by dudethatbe** [comment]
The submit button is disabled by default when you go to the application page and is enabled once you click on the checkbox. Should be good to go now

**Pull request merged**
